import { z } from "zod";

/**
 * The shape of web/tests/fixtures/preview-fixtures.json.
 *
 * Generated by device/notifier-app/tools/record_previews.py from the real
 * Python pages. The preview renders from these operations rather than from a
 * second reading of the layout, so the two cannot drift: change a device
 * layout, run `pnpm previews:fixtures`, and the preview changes with it.
 */

export const penOpSchema = z.object({ op: z.literal("pen"), value: z.string() });

export const rectOpSchema = z.object({
  op: z.literal("rect"),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
});

export const textOpSchema = z.object({
  op: z.literal("text"),
  text: z.string(),
  x: z.number(),
  y: z.number(),
  size: z.number(),
});

/** A headline drawn from the glyph table, recorded as the word rather than its pixels. */
export const blockOpSchema = z.object({
  op: z.literal("block"),
  text: z.string(),
  x: z.number(),
  y: z.number(),
  cell: z.number(),
});

export const shapeOpSchema = z.object({ op: z.literal("shape"), value: z.string() });

export const drawOpSchema = z.discriminatedUnion("op", [
  penOpSchema,
  rectOpSchema,
  textOpSchema,
  blockOpSchema,
  shapeOpSchema,
]);
export type DrawOp = z.infer<typeof drawOpSchema>;

export const pageFixtureSchema = z.object({
  name: z.string(),
  cases: z.record(
    z.string(),
    z.object({
      data: z.record(z.string(), z.unknown()),
      draw: z.array(drawOpSchema),
      leds: z.array(z.number()).nullable(),
    }),
  ),
  states: z.record(z.string(), z.array(drawOpSchema)),
});
export type PageFixture = z.infer<typeof pageFixtureSchema>;

export const previewFixturesSchema = z.object({
  screen: z.object({ w: z.number(), h: z.number() }),
  /** The ROM font names and the height each draws at, taken from ui.py. */
  fonts: z.record(z.string(), z.number()),
  pages: z.record(z.string(), pageFixtureSchema),
});
export type PreviewFixtures = z.infer<typeof previewFixturesSchema>;

/** The glyph cell the badge draws headlines from: five wide, seven tall. */
export const BLOCK_W = 5;
export const BLOCK_H = 7;
export const BLOCK_TRACKING = 1;

export function blockWidth(text: string, cell: number): number {
  return text.length * (BLOCK_W + BLOCK_TRACKING) * cell - BLOCK_TRACKING * cell;
}
