// POST /mcp-server. A stub, deliberately.
//
// Recall is shipping alongside BYO MCP, and this app should use that feature
// rather than hand-roll around it. Building a real MCP server now means throwing
// it away in three weeks and losing the better demo, which is Recall's MCP server
// generated by the product being launched.
//
// So the shape is here and nothing else is: the route is registered, auth runs
// through the same verified-JWT path as every other authenticated function, and
// there is one tool that proves the identity arrived. The intended contracts for
// the real tools are in docs/mcp.md.
//
// TODO(edge-functions): implement search, get_document, list_spaces and add_note
// on top of the Supabase Library mcp-server and oauth-consent-nextjs blocks, once
// BYO MCP ships. Until then this stub must not grow: a second tool here is a
// second thing to delete.

import { ApiError, jsonResponse } from '../_shared/errors.ts';
import { serveFunction } from '../_shared/http.ts';
import { requireUser } from '../_shared/auth.ts';
import { serviceClient } from '../_shared/db.ts';
import { enforceRateLimits } from '../_shared/rate_limit.ts';

const PROTOCOL_VERSION = '2025-06-18';

const WHOAMI = {
  name: 'whoami',
  description: 'Returns the Recall account this connection is acting as.',
  inputSchema: { type: 'object', properties: {}, additionalProperties: false },
} as const;

/** The four tools the real server will expose. Named so the stub is honest. */
const PLANNED_TOOLS = ['search', 'get_document', 'list_spaces', 'add_note'] as const;

serveFunction('mcp-server', async (core) => {
  const user = await requireUser(core.headers);
  const db = serviceClient();

  await enforceRateLimits(db, [
    { bucket: `mcp:user:${user.id}`, limit: 120, windowSeconds: 600 },
  ]);

  if (core.method !== 'POST') {
    throw new ApiError(405, 'method_not_allowed', 'this endpoint takes POST');
  }

  const request = typeof core.body === 'object' && core.body !== null
    ? (core.body as Record<string, unknown>)
    : {};
  const method = typeof request.method === 'string' ? request.method : '';

  switch (method) {
    case 'initialize':
      return jsonResponse({
        protocolVersion: PROTOCOL_VERSION,
        serverInfo: { name: 'recall', version: '0.1.0' },
        capabilities: { tools: {} },
      });

    case 'tools/list':
      return jsonResponse({ tools: [WHOAMI], planned: PLANNED_TOOLS });

    case 'tools/call': {
      const params = typeof request.params === 'object' && request.params !== null
        ? (request.params as Record<string, unknown>)
        : {};
      if (params.name !== WHOAMI.name) {
        throw new ApiError(400, 'unknown_tool', 'this server exposes only whoami for now');
      }
      return jsonResponse({
        content: [{ type: 'text', text: `Signed in as ${user.email ?? user.id}` }],
      });
    }

    default:
      throw new ApiError(400, 'unsupported_method', 'this stub answers initialize and tools only');
  }
});
